[package]
name = "depthso/regui"
description = "A retained recreation of ImGui for Roblox"
version = "1.4.0"
license = "MIT"
registry = "https://github.com/depthso/Dear-ReGui"
homepage = "https://depso.gitbook.io/regui"
include = ["lib", "ReGui.lua", "LICENSE"]
authors = ["depso <depthso>"]
realm = "shared"

[dependencies]